version: '3.6'
services:

  postgres:
    container_name: postgres
    image: bitnami/postgresql:15
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - backend
    environment:
      POSTGRES_USER: addressbook
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: addressbook_db

  addressbook_auth:
    container_name: auth
    image: andreyznsk/app:auth.latest
    networks:
      - backend
    ports:
      - "9003:9003"
    volumes:
      - ./addressbook_auth/env/docker/:/app/config
    depends_on:
      - addressbook_main

  addressbook_calc:
    container_name: calc
    image: andreyznsk/app:calc.latest
    networks:
      - backend
    ports:
      - "9002:9002"
    volumes:
      - ./addressbook_ageCalcFunction/env/docker/:/app/config
    depends_on:
      - addressbook_main

  addressbook_cache:
    container_name: cache
    image: andreyznsk/app:cache.latest
    networks:
      - backend
    ports:
      - "9005:9005"
    volumes:
      - ./addressbook_cache/env/docker/:/app/config
    environment:
      JAVA_OPTS: >
        --add-modules java.se
        --add-exports java.base/jdk.internal.ref=ALL-UNNAMED 
        --add-opens java.base/java.lang=ALL-UNNAMED 
        --add-opens java.base/sun.nio.ch=ALL-UNNAMED 
        --add-opens java.management/sun.management=ALL-UNNAMED 
        --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    depends_on:
      - postgres

  addressbook_main:
    image: andreyznsk/app:main.latest
    networks:
      - backend
    ports:
      - "9001"
    volumes:
      - ./addressbook_main/env/docker/:/app/config
    depends_on:
      - postgres
    deploy:
      replicas: 2
      labels:
        app: addressbook
        langugae: java
      resources:
        limits:
          cpus: "1.0"

volumes:
  elastic_data: {}
  data-db: {}

networks:
  backend:
