version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - backend

  Logstash:
    image: logstash:7.14.2
    container_name: logstash
    restart: always
    volumes:
    - ./elk/logstash/:/logstash_conf
    command: logstash -f /logstash_conf/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
    - '4501:4501'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - backend

  Kibana:
    image: kibana:7.14.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch  
    networks:
      - backend

volumes:
  elastic_data: {}
  data-db: {}

networks:
  backend:
