version: '3.6'
services:

  postgres:
    container_name: postgres
    image: bitnami/postgresql:15
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - backend
    environment:
      POSTGRES_USER: addressbook
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: addressbook_db

  addressbook_auth:
    container_name: auth
    image: andreyznsk/app:auth.latest
    networks:
      - backend
    ports:
      - "9003:9003"
    volumes:
      - ./addressbook_auth/env/docker/:/app/config
    depends_on:
      - addressbook_main

  addressbook_calc:
    container_name: calc
    image: andreyznsk/app:calc.latest
    networks:
      - backend
    ports:
      - "9002:9002"
    volumes:
      - ./addressbook_ageCalcFunction/env/docker/:/app/config
    depends_on:
      - addressbook_main

  addressbook_main:
    image: andreyznsk/app:main.latest
    networks:
      - backend
    ports:
      - "9001"
    volumes:
      - ./addressbook_main/env/docker/:/app/config
    depends_on:
      - postgres
    deploy:
      replicas: 2
      labels:
        app: addressbook
        langugae: java
      resources:
        limits:
          cpus: "2.0"

volumes:
  elastic_data: {}
  data-db: {}

networks:
  backend:
