version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - backend

  Logstash:
    image: logstash:7.14.2
    container_name: logstash
    restart: always
    volumes:
    - ./elk/logstash/:/logstash_conf
    command: logstash -f /logstash_conf/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
    - '4501:4501'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    networks:
      - backend

  Kibana:
    image: kibana:7.14.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - Elasticsearch
    networks:
      - backend

  postgres:
    container_name: postgres
    image: stage.sberosc.sigma.sbrf.ru/postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - backend
    environment:
      POSTGRES_USER: addressbook
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: addressbook_db
    depends_on:
      - Logstash

  addressbook_auth:
    container_name: auth
    image: addressbook/auth:latest
    networks:
      - backend
    ports:
      - "9003:9003"
    volumes:
      - ./addressbook_auth/env/docker/:/app/config
      - ./addressbook_auth/users/users.json:/app/users/users.json
    depends_on:
      - addressbook_main

  addressbook_calc:
    container_name: calc
    image: addressbook/calc:latest
    networks:
      - backend
    ports:
      - "9002:9002"
    volumes:
      - ./addressbook_ageCalcFunction/env/docker/:/app/config
    depends_on:
      - addressbook_main

  addressbook_main:
    container_name: main
    image: addressbook/main:latest
    networks:
      - backend
    ports:
      - "9001:9001"
    volumes:
      - ./addressbook_main/env/docker/:/app/config
    depends_on:
      - postgres

volumes:
  elastic_data: {}
  data-db: {}

networks:
  backend:
