#logging:
#  config: ./config/logback-spring.xml

server:
  port: 9001

spring:
  elk:
    host: Logstash
    port: 4501
app:
  module: main
  ageCalcFunc:
    host: http://calc
    port: 9002
    api: /api/v1/calcAge
  auth:
    host: http://auth
    port: 9003
    api: /api/v1/auth
  cache:
    host: http://cache
    port: 9005
    api: /api/v1/cache

