### Запросить все записи из БД
GET http://localhost:9001/api/v1/addressbooks
login: john

{}

### Запросить запись с возрастом

GET http://localhost:9001/api/v1/addressbookAge/2
Content-Type: application/json
login: john

{}

### запросить Юзера

POST http://localhost:9003/api/v1/auth

john

### Актуатор
GET http://localhost:9001/actuator/health

{}

### Get in OC Cluster Запросить все записи из БД
GET http://sbercode-28384620-1362-4d4a-93e2-dc4dcec64eee-work.apps.sbc-okd.pcbltools.ru/api/v1/addressbooks
login: john

### Get in OC Cluster Запросить запись с возрастом
GET http://sbercode-28384620-1362-4d4a-93e2-dc4dcec64eee-work.apps.sbc-okd.pcbltools.ru/api/v1/addressbookAge/2
login: john
