addressbook:
  cahe:
    hazelcast: |
      <hazelcast xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.hazelcast.com/schema/config
                   http://www.hazelcast.com/schema/config/hazelcast-config-4.2.xsd">

        <cluster-name>addressbbok-cluster</cluster-name>
        <network>
            <join>
                <multicast enabled="false"/>
                <kubernetes enabled="true"/>
            </join>
        </network>
      </hazelcast>
    appConfig: |
      #logging:
      #  config: /app/config/logback-spring.xml
      
      server:
        port: 9005
      
      spring:
        datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://db-service.zaytsevad.svc.cluster.local:5432/${POSTGRESQL_DATABASE}
          username: ${POSTGRESQL_USERNAME}
          password: ${POSTGRESQL_PASSWORD}
        jpa:
          database-platform: org.hibernate.dialect.PostgreSQL10Dialect
          hibernate:
            ddl-auto: none
          open-in-view: false
          properties:
            hibernate:
              dialect: org.hibernate.dialect.PostgreSQL10Dialect
              cache:
                region:
                  factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
                use_second_level_cache: true
                hazelcast:
                  configuration_file_path: /app/config/hazelcast.xml
          show-sql: true
        elk:
          host: logstash-service.zaytsevad.svc.cluster.local
          port: 4501