kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-cache
data:
  hazelcast.xml: |
    {{ .Values.addressbook.cahe.hazelcast | indent 4}}
  application.yaml: |
    {{ toYaml .Values.addressbook.cahe.appConfig | indent 4}}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-auth
data:
  application.yaml: |
    #logging:
    #  config: /app/config/logback-spring.xml
    server:
      port: 9003
    spring:
      elk:
        host: logstash-service.zaytsevad.svc.cluster.local
        port: 4501
    user:
      localDir: users/users.json
    app:
      module: auth
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-calc
data:
  application.yaml: |
    #logging:
    #  config: /app/config/logback-spring.xml
    server:
      port: 9002
    spring:
      elk:
        host: logstash-service.zaytsevad.svc.cluster.local
        port: 4501
    app:
      module: calc
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-main
data:
  application.yaml: |
    #logging:
    #  config: /app/config/logback-spring.xml
    server:
      port: 9001
    spring:
      elk:
        host: logstash-service.zaytsevad.svc.cluster.local
        port: 4501
    app:
      module: main
      ageCalcFunc:
        host: http://calc-service.zaytsevad.svc.cluster.local
        port: 9002
        api: /api/v1/calcAge
      auth:
        host: http://auth-service.zaytsevad.svc.cluster.local
        port: 9003
        api: /api/v1/auth
      cache:
        host: http://cache-service.zaytsevad.svc.cluster.local
        port: 9005
        api: /api/v1/cache