kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-cache
data:
  hazelcast.xml: |
    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.hazelcast.com/schema/config
             http://www.hazelcast.com/schema/config/hazelcast-config-4.2.xsd">

      <cluster-name>addressbbok-cluster</cluster-name>
      <network>
          <join>
              <multicast enabled="false"/>
              <kubernetes enabled="true"/>
          </join>
      </network>
    </hazelcast>
  application.yaml: |
    #logging:
    #  config: /app/config/logback-spring.xml

    server:
      port: 9005

    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db-service.zaytsevad.svc.cluster.local:5432/${POSTGRESQL_DATABASE}
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate:
          ddl-auto: none
        open-in-view: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            cache:
              region:
                factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
              use_second_level_cache: true
              hazelcast:
                configuration_file_path: /app/config/hazelcast.xml
        show-sql: true
      elk:
        host: logstash-service.zaytsevad.svc.cluster.local
        port: 4501
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-auth
data:
  application.yaml: |
    #logging:
    #  config: /app/config/logback-spring.xml
    server:
      port: 9003
    spring:
      elk:
        host: logstash-service.zaytsevad.svc.cluster.local
        port: 4501
    user:
      localDir: users/users.json
    app:
      module: auth
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-calc
data:
  application.yaml: |
    #logging:
    #  config: /app/config/logback-spring.xml
    server:
      port: 9002
    spring:
      elk:
        host: logstash-service.zaytsevad.svc.cluster.local
        port: 4501
    app:
      module: calc
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-main
data:
  application.yaml: |
    #logging:
    #  config: /app/config/logback-spring.xml
    server:
      port: 9001
    spring:
      elk:
        host: logstash-service.zaytsevad.svc.cluster.local
        port: 4501
    app:
      module: main
      ageCalcFunc:
        host: http://calc-service.zaytsevad.svc.cluster.local
        port: 9002
        api: /api/v1/calcAge
      auth:
        host: http://auth-service.zaytsevad.svc.cluster.local
        port: 9003
        api: /api/v1/auth
      cache:
        host: http://cache-service.zaytsevad.svc.cluster.local
        port: 9005
        api: /api/v1/cache