kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-main
data:
  application.yaml: |
    logging:
      config: ./config/logback-spring.xml
    
    server:
      port: 9001
    
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: postgres://db.NAMESPACE.svc.cluster.local:5432/${POSTGRESQL_DATABASE}
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate:
          ddl-auto: none
        open-in-view: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show-sql: false
      elk:
        host: Logstash.NAMESPACE.svc.cluster.local
        port: 4501
    app:
      module: main
      ageCalcFunc:
        host: http://calc.NAMESPACE.svc.cluster.local
        port: 9002
        api: /api/v1/calcAge
      auth:
        host: http://auth.NAMESPACE.svc.cluster.local
        port: 9003
        api: /api/v1/auth
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-auth
data:
  application.yaml: |
    logging:
      config: ./config/logback-spring.xml
    server:
      port: 9003
    spring:
      elk:
        host: Logstash.NAMESPACE.svc.cluster.local
        port: 4501
    user:
      localDir: users/users.json
    app:
      module: auth
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config-calc
data:
  application.yaml: |
    logging:
      config: ./config/logback-spring.xml
    server:
      port: 9002
    spring:
      elk:
        host: Logstash.NAMESPACE.svc.cluster.local
        port: 4501
    app:
      module: calc