kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-config
data:
  logstash.conf : |
    input {
      tcp {
        port => 4501
        codec => json_lines
      }
    }
    filter {
      mutate {
        remove_field => [ "host" ]
      }
      date {
        match => [ "timeMillis", "UNIX_MS" ]
      }
    }
    output {
      elasticsearch {
        hosts => "http://elasticsearch.sbercode-29458557-11d6-4ac2-95c0-9673a35ec176-work.svc.cluster.local:9200"
        index => "addressbook"
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jvm-opt
data:
  ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  LS_JAVA_OPTS: "-Xmx256m -Xms256m"
