kind: Deployment
apiVersion: apps/v1
metadata:
  name: addressbook-main
  labels:
    app: addressbook-main_lable_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook-main
  template:
    metadata:
      labels:
        app: addressbook-main
    spec:
      containers:
        - name: addressbook-main-app
          restartPolicy: never
          image: andreyznsk/app:main.latest
          ports:
            - name: http
              containerPort: 9001
          volumeMounts:
            - name: addressbook-cfg-vol
              mountPath: /app/config/application.yaml
            - name: logback-config-vol
              mountPath: /app/config/logback-spring.xml
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-password
          livnessProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureTrashold: 100
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: http
      volumes:
        - name: addressbook-cfg-vol
          configMap:
            name: addressbook-config-main
        - name: logback-config-vol
          configMap:
            name: logback-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: addressbook-calc
  labels:
    app: addressbook-calc_lable_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook-calc
  template:
    metadata:
      labels:
        app: addressbook-calc
    spec:
      containers:
        - name: addressbook-calc-app
          restartPolicy: never
          image: andreyznsk/app:calc.latest
          ports:
            - name: http
              containerPort: 9002
          volumeMounts:
            - name: addressbook-cfg-vol
              mountPath: /app/config/application.yaml
            - name: logback-config-vol
              mountPath: /app/config/logback-spring.xml
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-password
          livnessProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureTrashold: 100
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: http
      volumes:
        - name: addressbook-cfg-vol
          configMap:
            name: addressbook-config-calc
        - name: logback-config-vol
          configMap:
            name: logback-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: addressbook-auth
  labels:
    app: addressbook-auth_lable_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook-auth
  template:
    metadata:
      labels:
        app: addressbook-auth
    spec:
      containers:
        - name: addressbook-auth-app
          restartPolicy: never
          image: andreyznsk/app:auth.latest
          ports:
            - name: http
              containerPort: 9003
          volumeMounts:
            - name: addressbook-cfg-vol
              mountPath: /app/config/application.yaml
            - name: logback-config-vol
              mountPath: /app/config/logback-spring.xml
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-password
          livnessProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureTrashold: 100
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: http
      volumes:
        - name: addressbook-cfg-vol
          configMap:
            name: addressbook-config-auth
        - name: logback-config-vol
          configMap:
            name: logback-config
