kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: switch
  lables:
    app: switch
spec:
  rules:
    - host: sbercode-28384620-1362-4d4a-93e2-dc4dcec64eee-work.apps.sbc-okd.pcbltools.ru
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: addresbook-main-service
                port:
                  name: main-api


