kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: main-app
  lables:
    app: main-app
spec:
  rules:
    - host: zaytsevad.apps.okd.sbc-openshift.ru
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  name: main-api


