server:
  port: ${serverPort:9990}

logging:
  file:
    name: logs/tmpAdz.log

spring:
  elk:
    host: localHost
    port: 4501
app:
  module: main
  ageCalcFunc:
    host: http://localhost
    port: 9002
    api: /api/v1/calcAge
  auth:
    host: http://localhost
    port: 9003
    api: /api/v1/auth
  cache:
    host: http://localhost
    port: 9005
    api: /api/v1/cache

